/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package codechallengestest;

import codechallenges.utilities.Library;
import org.junit.Test;
import static org.junit.Assert.*;

public class LibraryTest {
    @Test public void testSomeLibraryMethod() {
        Library classUnderTest = new Library();
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }
}
