/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package codeChallenges.utilities;

public class Library {
    public boolean someLibraryMethod() {
        System.out.println("HELLOOOOOO");
        return true;
    }
}
