/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package DataStructures;

import DataStructures.linkedlist.LinkedList;

public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) throws Exception {
        LinkedList newList = new LinkedList();
        newList.addToFront(2);
        newList.addToFront(6);
        newList.addToFront(12);
        newList.addToFront(23);
        newList.addToFront(115);

//        newList.addToEnd(13);
//        newList.addBeforeValue(2,10);
//        newList.addAfterValue(12,115);

        System.out.println(newList);

//        returns nth value from end:

        System.out.println(newList.nthValueFromEnd(0));
    }
}
