/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package DataStructures;

import DataStructures.linkedlist.LinkedList;

public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        LinkedList newList = new LinkedList();
        newList.addToFront(2);
        newList.addToFront(6);
        newList.addToFront(12);

        newList.addToEnd(13);

//        try {
//            newList.removeFromEnd();
//        } catch (Exception e) {
//            e.printStackTrace();
//        }

        System.out.println(newList);
    }
}
