/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package DataStructures;

import DataStructures.linkedlist.LinkedList;
import DataStructures.stacksandqueues.Queue;
import DataStructures.stacksandqueues.Stack;
import DataStructures.stacksandqueues.PsuedoQueue;

public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) throws Exception {

//        ----- Linked Lists -----
        LinkedList L1 = new LinkedList();
        LinkedList L2 = new LinkedList();

        L1.addToFront(2);
        L1.addToFront(3);
        L1.addToFront(1);

        L2.addToFront(4);
        L2.addToFront(9);
        L2.addToFront(5);

//        ----- Queues -----
        Queue newQueue = new Queue();
        newQueue.enQueue(7);
        newQueue.enQueue(8);
        newQueue.enQueue(9);
        newQueue.enQueue(24);
        newQueue.deQueue();
        int peekVal = newQueue.peek();

//        System.out.println("Queue : " + newQueue);
//        System.out.println("peek: " + peekVal);
//        System.out.println(newQueue.isEmpty());
//        System.out.println();

//        ----- Stacks -----
//        Stack newStack = new Stack();
//        newStack.push(10);      // head
//        newStack.push(24);      // ---
//        newStack.push(666);     // tail

//        ----- PseudoQueue -----
        PsuedoQueue psuedo = new PsuedoQueue();

        psuedo.enQueue(5);
        psuedo.enQueue(10);
        psuedo.enQueue(15);
        System.out.println(psuedo);

        psuedo.enQueue(20);
        System.out.println(psuedo);
        System.out.println("Top of Stack: " + psuedo.deQueue());

//        System.out.println("Stack : " + newStack);
//        System.out.println("peek : " + newStack.peek() );
//        System.out.println("Pop (666) : " + newStack.pop() );

    }
}
